/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Annotations
         * @description Gene annotations, best BUSCO first by default; records missing the sort field
         *     come last. The quality stats of a taxon's annotations are in ``/taxons/{taxid}/stats``.
         */
        get: operations["annotations_annotations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assemblies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Assemblies
         * @description Genome assemblies, newest first by default; records missing the sort field
         *     come last. The quality stats of a taxon's assemblies are in ``/taxons/{taxid}/stats``.
         */
        get: operations["assemblies_assemblies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config
         * @description What a client reads once before showing any data: the dataset being served
         *     (``built_at`` is ``null`` before the first build has stamped the database), the
         *     presentation of each measure and quality stat, and the deployment's links,
         *     Wikipedia summary endpoint, curated groups and custom groups. Pass a custom
         *     group's clades to ``/taxons/aggregates`` for its data.
         */
        get: operations["config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process is up and serving. Checks no dependencies, so a
         *     container/orchestrator can tell 'process alive' apart from 'DB ready'.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness: can we actually serve reads? Pings Postgres with SELECT 1 and
         *     returns 503 if it's unreachable, so a load balancer holds traffic until the
         *     read-only serving DB is back.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxons
         * @description Taxa with their counts: a name search (``q``), a taxon's children
         *     (``parent``), every taxon of a rank under a taxon (``within`` and ``rank``), or
         *     chosen taxa (``taxids``), narrowed by the data they have. Sort by
         *     ``gap_<resource>`` for the groups with the most species still missing it. Their
         *     quality stats are in ``/taxons/stats``.
         */
        get: operations["taxons_taxons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxons/aggregates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate
         * @description Species count, per-resource coverage and quality stats for a set of clades:
         *     the clades in ``include`` minus the clades inside them in ``exclude`` (e.g.
         *     fish as Vertebrata minus Tetrapoda). A clade inside an excluded one can be
         *     included again. Counts are sums and differences of the clades' rollups;
         *     quality stats are computed from the records in the set. A list, like every
         *     collection, holding the one set asked for.
         */
        get: operations["aggregate_taxons_aggregates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxons/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxons Report
         * @description Every taxon ``/taxons`` lists for the same filters and sort, as a streamed
         *     TSV download: taxid, name, species count, then the species with each resource
         *     and the total of each resource. Not cached: a report runs to tens of MB, and
         *     nginx's cache is kept for the small responses the interface repeats.
         */
        get: operations["taxons_report_taxons_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxons/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxons Stats
         * @description The quality stats (best BUSCO, median genes, genome size and N50) of the taxa
         *     ``/taxons`` lists for the same parameters, page for page and with the same
         *     cursors, each over the records on or below the taxon. Computed at build time,
         *     so a page costs about what the same page of ``/taxons`` does.
         */
        get: operations["taxons_stats_taxons_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxons/{taxid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon
         * @description One taxon, the same object ``/taxons`` lists: species count, per-resource
         *     coverage and assembly composition. A species, an informal species or a finer
         *     taxon also has ``direct``: its records attached to the taxon itself rather than
         *     to a finer taxon below it.
         */
        get: operations["taxon_taxons__taxid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxons/{taxid}/ancestors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon Ancestors
         * @description The root, every taxon below it down to this one, and this one, in that order,
         *     as the same objects ``/taxons`` lists. One page: a lineage is at most a few
         *     dozen taxa.
         */
        get: operations["taxon_ancestors_taxons__taxid__ancestors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxons/{taxid}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon Stats
         * @description The quality stats (best BUSCO, median genes, genome size and N50) of the
         *     records on or below one taxon, the same object ``/taxons/stats`` lists,
         *     computed at build time.
         */
        get: operations["taxon_stats_taxons__taxid__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aggregate
         * @description Species count, per-resource coverage and quality stats for a set of clades
         *     (served by ``/taxons/aggregates``): a taxon is in the set when the nearest listed
         *     clade above it (or the taxon itself) is in ``include``.
         */
        Aggregate: {
            composition: components["schemas"]["AssemblyComposition"];
            /** Exclude */
            exclude: components["schemas"]["TaxonRef"][];
            /** Include */
            include: components["schemas"]["TaxonRef"][];
            /** N Rows */
            n_rows: number;
            /** Resources */
            resources: {
                [key: string]: components["schemas"]["ResourceSummary"];
            };
            /**
             * Stats
             * @description As for a taxon, over the records in the set.
             */
            stats: components["schemas"]["QualityStatValue"][];
        };
        /** AggregatePage */
        AggregatePage: {
            /** Limit */
            limit: number;
            /** Next */
            next: string | null;
            /** Previous */
            previous: string | null;
            /** Results */
            results: components["schemas"]["Aggregate"][];
            /** Total */
            total: number;
        };
        /** AnnotationPage */
        AnnotationPage: {
            /** Limit */
            limit: number;
            /** Next */
            next: string | null;
            /** Previous */
            previous: string | null;
            /** Results */
            results: components["schemas"]["AnnotationRecord"][];
            /** Total */
            total: number;
        };
        /**
         * AnnotationRecord
         * @description One functional annotation (from the ``annotation`` table), for the
         *     drill-down list — the Annotrieve-sourced BUSCO + gene metadata + GFF link.
         */
        AnnotationRecord: {
            /** Annotation Id */
            annotation_id: string;
            /** Assembly Accession */
            assembly_accession: string | null;
            /** Busco Complete */
            busco_complete: number | null;
            /** Busco Duplicated */
            busco_duplicated: number | null;
            /** Busco Lineage */
            busco_lineage: string | null;
            /** Busco Single Copy */
            busco_single_copy: number | null;
            /** Gene Count */
            gene_count: number | null;
            /** Gff Url */
            gff_url: string | null;
            /** Organism */
            organism: string;
            /** Protein Coding Count */
            protein_coding_count: number | null;
            /** Provider */
            provider: string | null;
            /** Release Date */
            release_date: string | null;
            /** Source Database */
            source_database: string | null;
            /** Taxid */
            taxid: number;
        };
        /**
         * AnnotationSort
         * @enum {string}
         */
        AnnotationSort: "busco_complete" | "protein_coding_count" | "release_date";
        /**
         * AppConfig
         * @description What a client reads once before showing any data (served by ``/config``):
         *     the dataset it is looking at, how to present each measure, and the
         *     deployment's links and groups.
         */
        AppConfig: {
            /** Custom Groups */
            custom_groups: components["schemas"]["CustomGroupItem"][];
            dataset: components["schemas"]["DatasetMeta"];
            /** Feedback Url */
            feedback_url: string;
            /** Groups */
            groups: components["schemas"]["CladeGroup"][];
            /** Metrics */
            metrics: components["schemas"]["MetricConfig"][];
            /** Privacy Contact Email */
            privacy_contact_email: string;
            /** Quality Stats */
            quality_stats: components["schemas"]["QualityStatConfig"][];
            /** Source Code Url */
            source_code_url: string;
            /** Wikipedia Summary Url */
            wikipedia_summary_url: string;
        };
        /**
         * AssemblyComposition
         * @description The genome assemblies on or below a taxon by assembly level, and how many
         *     are NCBI reference or representative genomes; summed when the dataset is
         *     built, like the resource totals.
         */
        AssemblyComposition: {
            /** Chromosome */
            chromosome: number;
            /** Complete */
            complete: number;
            /** Contig */
            contig: number;
            /**
             * Reference
             * @description Assemblies NCBI marks as reference or representative.
             */
            reference: number;
            /** Scaffold */
            scaffold: number;
        };
        /** AssemblyPage */
        AssemblyPage: {
            /** Limit */
            limit: number;
            /** Next */
            next: string | null;
            /** Previous */
            previous: string | null;
            /** Results */
            results: components["schemas"]["AssemblyRecord"][];
            /** Total */
            total: number;
        };
        /**
         * AssemblyRecord
         * @description One genome assembly (from the ``assembly`` table), for the drill-down list.
         *     Fields mirror the aliased SELECT so the endpoint builds it from a dict_row.
         */
        AssemblyRecord: {
            /** Assembly Accession */
            assembly_accession: string;
            /** Assembly Level */
            assembly_level: string | null;
            /** Bioprojects */
            bioprojects: string[];
            /** Contig N50 */
            contig_n50: number | null;
            /** Download Url */
            download_url: string | null;
            /** Gc Percent */
            gc_percent: number | null;
            /** Organism */
            organism: string;
            /** Refseq Category */
            refseq_category: string | null;
            /** Release Date */
            release_date: string | null;
            /** Scaffold N50 */
            scaffold_n50: number | null;
            /** Source Database */
            source_database: string | null;
            /** Submitter */
            submitter: string | null;
            /** Taxid */
            taxid: number;
            /** Total Sequence Length */
            total_sequence_length: number | null;
        };
        /**
         * AssemblySort
         * @enum {string}
         */
        AssemblySort: "release_date" | "contig_n50" | "total_sequence_length";
        /**
         * CladeGroup
         * @description A curated group: its friendly label is shown wherever the group appears,
         *     it is in the "Surprise me" pool, and ``featured`` groups are the landing-page
         *     cards. Also the entry format of the deployment's groups file.
         */
        CladeGroup: {
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /** Label */
            label: string;
            /** Taxid */
            taxid: number;
        };
        /**
         * CustomGroupItem
         * @description One custom group from the groups file. ``include`` and ``exclude`` are the
         *     clades it is made of, worked out from the parent's other groups for a
         *     ``rest`` group, so they can be passed to ``/taxons/aggregates`` as they are. A rest
         *     group with nothing left lists no clades.
         */
        CustomGroupItem: {
            /** Exclude */
            exclude: components["schemas"]["TaxonRef"][];
            /** Id */
            id: string;
            /** Include */
            include: components["schemas"]["TaxonRef"][];
            /** Label */
            label: string;
            /** Parent */
            parent: string | null;
            /** Rest */
            rest: boolean;
        };
        /**
         * DatasetMeta
         * @description Dataset provenance for the "Data updated" stamp — when the served dataset
         *     was built and how many records it holds. ``built_at`` is ``null`` before the
         *     first build has stamped the DB, in which case the frontend omits the stamp.
         */
        DatasetMeta: {
            /** Annotation Count */
            annotation_count: number;
            /** Assembly Count */
            assembly_count: number;
            /** Built At */
            built_at: string | null;
            /** Clade Count */
            clade_count: number;
            /** Taxon Count */
            taxon_count: number;
        };
        /**
         * FilterLogic
         * @description How multiple resource-presence filters combine (ported verbatim).
         * @enum {string}
         */
        FilterLogic: "AND" | "OR";
        /**
         * MetricConfig
         * @description Static per-resource card chrome — served once in ``/config`` and joined
         *     client-side to the numbers in each per-clade payload (by ``key``).
         */
        MetricConfig: {
            /** Card Title */
            card_title: string;
            /** Card Title Help */
            card_title_help: string | null;
            /** Color */
            color: string;
            /** Coverage Column */
            coverage_column: string;
            /** Empty Text */
            empty_text: string;
            /** External Source Name */
            external_source_name: string;
            /** External Url Template */
            external_url_template: string;
            /** Filter Label */
            filter_label: string;
            /** Key */
            key: string;
            /** Legend Label */
            legend_label: string;
            /** Overlay */
            overlay: boolean;
            /** Side */
            side: string;
            /** Sort Count Label */
            sort_count_label: string;
            /** Sort Total Label */
            sort_total_label: string;
            /** Species Help */
            species_help: string;
            /** Total Column */
            total_column: string;
            /** Total Help */
            total_help: string;
            /** Total Label */
            total_label: string;
        };
        /**
         * MetricFilter
         * @enum {string}
         */
        MetricFilter: "ass" | "ann" | "rna" | "lng";
        /**
         * ParameterError
         * @description One parameter a request got wrong.
         */
        ParameterError: {
            /** Detail */
            detail: string;
            /** Parameter */
            parameter: string;
        };
        /**
         * Problem
         * @description Every error response: problem details (RFC 9457), sent as
         *     ``application/problem+json``.
         */
        Problem: {
            /** Detail */
            detail: string;
            /** Errors */
            errors?: components["schemas"]["ParameterError"][] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * QualityStatConfig
         * @description Static chrome for one quality stat — served once in ``/config`` and
         *     joined client-side to the per-taxon ``QualityStatValue`` by ``key``.
         *     The analogue of ``MetricConfig`` for the annotation/assembly-quality
         *     dimension (BUSCO %, gene count, genome size, N50).
         */
        QualityStatConfig: {
            /**
             * Aggregation
             * @description How the records' values are summarized: their median or their maximum.
             * @enum {string}
             */
            aggregation: "median" | "max";
            /** Card Title */
            card_title: string;
            /** Fmt */
            fmt: string;
            /** Headline */
            headline: boolean;
            /** Help */
            help: string;
            /** Key */
            key: string;
            /** Source */
            source: string;
            /** Unit */
            unit: string | null;
        };
        /**
         * QualityStatValue
         * @description A quality stat of a taxon: the median or the maximum (see ``aggregation`` in
         *     ``/config``) of one field over the records on or below it.
         */
        QualityStatValue: {
            /** Key */
            key: string;
            /**
             * Value
             * @description Null when no record under the taxon has the field.
             */
            value: number | null;
        };
        /**
         * ResourceSummary
         * @description One resource's counts for a taxon, summed over the taxon and everything
         *     below it when the dataset is built.
         */
        ResourceSummary: {
            /**
             * Covered
             * @description Species on or below the taxon with at least one record.
             */
            covered: number;
            /**
             * Percent
             * @description covered / n_rows * 100, or 0 when n_rows is 0.
             */
            percent: number;
            /**
             * Total
             * @description Records on or below the taxon, at any rank.
             */
            total: number;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * TargetRank
         * @enum {string}
         */
        TargetRank: "phylum" | "class" | "order" | "family" | "genus" | "species";
        /**
         * Taxon
         * @description One taxon: the object ``/taxons/{taxid}`` returns and ``/taxons`` lists. Its
         *     ancestors are in ``/taxons/{taxid}/ancestors`` and its quality stats in
         *     ``/taxons/{taxid}/stats``.
         */
        Taxon: {
            composition: components["schemas"]["AssemblyComposition"];
            /**
             * Context
             * @description Nearest class, phylum or kingdom above the taxon, to tell homonyms apart.
             */
            context: string | null;
            /**
             * Direct
             * @description Species and finer taxa only: per resource, the records on the taxon itself; the rest of each total is on the taxa below it.
             */
            direct?: {
                [key: string]: number;
            } | null;
            /** Has Children */
            has_children: boolean;
            /**
             * Is Infraspecific
             * @description Below a species (subspecies, strain, ...): one unit whose data also counts for its species.
             * @default false
             */
            is_infraspecific: boolean;
            /**
             * N Rows
             * @description Species on or below the taxon (1 for a species or a finer taxon).
             */
            n_rows: number;
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /**
             * Resources
             * @description Per resource, keyed by the metric keys in /config.
             */
            resources: {
                [key: string]: components["schemas"]["ResourceSummary"];
            };
            /** Taxid */
            taxid: number;
        };
        /** TaxonPage */
        TaxonPage: {
            /** Limit */
            limit: number;
            /** Next */
            next: string | null;
            /** Previous */
            previous: string | null;
            /** Results */
            results: components["schemas"]["Taxon"][];
            /** Total */
            total: number;
        };
        /**
         * TaxonRef
         * @description Minimal taxon reference (breadcrumb / breakdown root).
         */
        TaxonRef: {
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /** Taxid */
            taxid: number;
        };
        /**
         * TaxonSort
         * @enum {string}
         */
        TaxonSort: "n_rows" | "c_ass" | "c_ann" | "c_rna" | "c_lng" | "s_ass" | "s_ann" | "s_rna" | "s_lng" | "n_ass_complete" | "n_ass_chromosome" | "n_ass_scaffold" | "n_ass_contig" | "n_reference" | "gap_ass" | "gap_ann" | "gap_rna" | "gap_lng" | "name";
        /**
         * TaxonStats
         * @description The quality stats of one taxon: the object ``/taxons/{taxid}/stats`` returns
         *     and ``/taxons/stats`` lists.
         */
        TaxonStats: {
            /** Name */
            name: string;
            /**
             * Stats
             * @description As in /taxons/{taxid}: computed per request from every record on or below the taxon; /config says which aggregation each one is.
             */
            stats: components["schemas"]["QualityStatValue"][];
            /** Taxid */
            taxid: number;
        };
        /** TaxonStatsPage */
        TaxonStatsPage: {
            /** Limit */
            limit: number;
            /** Next */
            next: string | null;
            /** Previous */
            previous: string | null;
            /** Results */
            results: components["schemas"]["TaxonStats"][];
            /** Total */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    annotations_annotations_get: {
        parameters: {
            query?: {
                /** @description Only rows on this taxon or below it (e.g. 40674 for mammals). */
                within?: number | null;
                sort_by?: components["schemas"]["AnnotationSort"];
                sort_order?: components["schemas"]["SortOrder"];
                limit?: number;
                /** @description ``next`` or ``previous`` from a page with the same sort, for the page after or before it. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotationPage"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assemblies_assemblies_get: {
        parameters: {
            query?: {
                /** @description Only rows on this taxon or below it (e.g. 40674 for mammals). */
                within?: number | null;
                sort_by?: components["schemas"]["AssemblySort"];
                sort_order?: components["schemas"]["SortOrder"];
                limit?: number;
                /** @description ``next`` or ``previous`` from a page with the same sort, for the page after or before it. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyPage"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    taxons_taxons_get: {
        parameters: {
            query?: {
                /** @description A count column, `gap_<resource>` (species without that resource) or `name`. Without it: relevance for `q`, else species count (`n_rows`). */
                sort_by?: components["schemas"]["TaxonSort"] | null;
                sort_order?: components["schemas"]["SortOrder"];
                limit?: number;
                /** @description ``next`` or ``previous`` from a page with the same sort, for the page after or before it. */
                cursor?: string | null;
                /** @description Only taxa whose name contains this text, ignoring case (or is spelled like it, with `fuzzy`). The root and 'cellular organisms' are left out. */
                q?: string | null;
                /** @description Match `q` by spelling instead, for a misspelt name. */
                fuzzy?: boolean;
                /** @description Only the direct children of this taxon. */
                parent?: number | null;
                /** @description Only rows on this taxon or below it (e.g. 40674 for mammals). */
                within?: number | null;
                /** @description Only taxa of this rank. */
                rank?: components["schemas"]["TargetRank"] | null;
                /** @description Only these taxa: comma-separated taxids, at most 100. */
                taxids?: string | null;
                /** @description Only taxa with data for these resources. */
                filter?: components["schemas"]["MetricFilter"][] | null;
                /** @description Whether `filter` needs every resource (AND) or any (OR). */
                logic?: components["schemas"]["FilterLogic"];
                /** @description Only taxa with data for at least one resource. */
                exclude_empty?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonPage"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    aggregate_taxons_aggregates_get: {
        parameters: {
            query: {
                /** @description Comma-separated taxids of the clades to add up (1-20, e.g. 7742). */
                include: string;
                /** @description Comma-separated taxids of clades inside them to leave out (e.g. 32523). */
                exclude?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregatePage"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    taxons_report_taxons_report_get: {
        parameters: {
            query?: {
                /** @description A count column, `gap_<resource>` (species without that resource) or `name`. Without it: relevance for `q`, else species count (`n_rows`). */
                sort_by?: components["schemas"]["TaxonSort"] | null;
                sort_order?: components["schemas"]["SortOrder"];
                /** @description Only taxa whose name contains this text, ignoring case (or is spelled like it, with `fuzzy`). The root and 'cellular organisms' are left out. */
                q?: string | null;
                /** @description Match `q` by spelling instead, for a misspelt name. */
                fuzzy?: boolean;
                /** @description Only the direct children of this taxon. */
                parent?: number | null;
                /** @description Only rows on this taxon or below it (e.g. 40674 for mammals). */
                within?: number | null;
                /** @description Only taxa of this rank. */
                rank?: components["schemas"]["TargetRank"] | null;
                /** @description Only these taxa: comma-separated taxids, at most 100. */
                taxids?: string | null;
                /** @description Only taxa with data for these resources. */
                filter?: components["schemas"]["MetricFilter"][] | null;
                /** @description Whether `filter` needs every resource (AND) or any (OR). */
                logic?: components["schemas"]["FilterLogic"];
                /** @description Only taxa with data for at least one resource. */
                exclude_empty?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    taxons_stats_taxons_stats_get: {
        parameters: {
            query?: {
                /** @description A count column, `gap_<resource>` (species without that resource) or `name`. Without it: relevance for `q`, else species count (`n_rows`). */
                sort_by?: components["schemas"]["TaxonSort"] | null;
                sort_order?: components["schemas"]["SortOrder"];
                limit?: number;
                /** @description ``next`` or ``previous`` from a page with the same sort, for the page after or before it. */
                cursor?: string | null;
                /** @description Only taxa whose name contains this text, ignoring case (or is spelled like it, with `fuzzy`). The root and 'cellular organisms' are left out. */
                q?: string | null;
                /** @description Match `q` by spelling instead, for a misspelt name. */
                fuzzy?: boolean;
                /** @description Only the direct children of this taxon. */
                parent?: number | null;
                /** @description Only rows on this taxon or below it (e.g. 40674 for mammals). */
                within?: number | null;
                /** @description Only taxa of this rank. */
                rank?: components["schemas"]["TargetRank"] | null;
                /** @description Only these taxa: comma-separated taxids, at most 100. */
                taxids?: string | null;
                /** @description Only taxa with data for these resources. */
                filter?: components["schemas"]["MetricFilter"][] | null;
                /** @description Whether `filter` needs every resource (AND) or any (OR). */
                logic?: components["schemas"]["FilterLogic"];
                /** @description Only taxa with data for at least one resource. */
                exclude_empty?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonStatsPage"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    taxon_taxons__taxid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Taxon"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    taxon_ancestors_taxons__taxid__ancestors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonPage"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    taxon_stats_taxons__taxid__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonStats"];
                };
            };
            /** @description An error, as problem details (RFC 9457). */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
