/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clade/{taxid}/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clade Breakdown
         * @description How a clade's data is distributed at a lower rank (Q2).
         *
         *     Descendants of `taxid` at `rank`, with filter/sort/limit pushed into a
         *     single indexed `ltree` query. Defaults mirror Euka-Survey: sort by species
         *     count, exclude empty taxa, AND-combine filters, top 25.
         */
        get: operations["clade_breakdown_clade__taxid__breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clade/{taxid}/export.tsv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clade Export
         * @description The full breakdown at `rank` as a streamed TSV download.
         *
         *     Same subtree query as `breakdown` but unlimited and streamed via a
         *     server-side cursor. Defaults to the complete breakdown (empties included);
         *     pass filter/exclude_empty/sort to export exactly what the table shows.
         */
        get: operations["clade_export_clade__taxid__export_tsv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clade/{taxid}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clade Summary
         * @description Genomic Resource Summary for one taxon: species count + per-resource
         *     coverage/total/percent. One indexed lookup on `clade_features`.
         */
        get: operations["clade_summary_clade__taxid__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Config
         * @description The tracked metrics — static card chrome the frontend renders once,
         *     keyed by the same metric keys the per-clade payloads use.
         */
        get: operations["metrics_config_metrics_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Case-insensitive taxon-name search for the root picker. Substring match,
         *     prefix-matches first (served by the `pg_trgm` GIN index on `taxon.name`).
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxon/{taxid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon Lineage
         * @description The taxon and its root→node lineage (breadcrumb). One indexed `ltree`
         *     ancestor query on the materialized path.
         */
        get: operations["taxon_lineage_taxon__taxid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Breakdown
         * @description The breakdown (Q2) payload: a root's descendants at a target rank.
         */
        Breakdown: {
            /** Items */
            items: components["schemas"]["CladeSummary"][];
            /** Rank */
            rank: string;
            /** Returned */
            returned: number;
            root: components["schemas"]["TaxonRef"];
            /** Total Matches */
            total_matches: number;
        };
        /**
         * CladeSummary
         * @description The Genomic Resource Summary (Q1) payload for one taxon.
         */
        CladeSummary: {
            /** N Rows */
            n_rows: number;
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /** Resources */
            resources: {
                [key: string]: components["schemas"]["ResourceSummary"];
            };
            /** Taxid */
            taxid: number;
        };
        /**
         * FilterLogic
         * @description How multiple resource-presence filters combine (ported verbatim).
         * @enum {string}
         */
        FilterLogic: "AND" | "OR";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MetricConfig
         * @description Static per-resource card chrome — served once by ``/metrics-config`` and
         *     joined client-side to the numbers in each per-clade payload (by ``key``).
         */
        MetricConfig: {
            /** Card Title */
            card_title: string;
            /** Card Title Help */
            card_title_help: string | null;
            /** Color */
            color: string;
            /** Coverage Column */
            coverage_column: string;
            /** External Source Name */
            external_source_name: string;
            /** External Url Template */
            external_url_template: string;
            /** Filter Label */
            filter_label: string;
            /** Key */
            key: string;
            /** Legend Label */
            legend_label: string;
            /** Overlay */
            overlay: boolean;
            /** Side */
            side: string;
            /** Sort Count Label */
            sort_count_label: string;
            /** Sort Total Label */
            sort_total_label: string;
            /** Species Help */
            species_help: string;
            /** Total Column */
            total_column: string;
            /** Total Help */
            total_help: string;
            /** Total Label */
            total_label: string;
        };
        /**
         * MetricFilter
         * @enum {string}
         */
        MetricFilter: "ass" | "ann" | "rna" | "lng";
        /**
         * ResourceSummary
         * @description Per-resource rollup for one clade.
         */
        ResourceSummary: {
            /** Covered */
            covered: number;
            /** Percent */
            percent: number;
            /** Total */
            total: number;
        };
        /**
         * SortColumn
         * @enum {string}
         */
        SortColumn: "n_rows" | "c_ass" | "c_ann" | "c_rna" | "c_lng" | "s_ass" | "s_ann" | "s_rna" | "s_lng";
        /**
         * TargetRank
         * @enum {string}
         */
        TargetRank: "phylum" | "class" | "order" | "family" | "genus" | "species";
        /**
         * TaxonLineage
         * @description A taxon plus its root→node lineage (for the header breadcrumb).
         */
        TaxonLineage: {
            /** Lineage */
            lineage: components["schemas"]["TaxonRef"][];
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /** Taxid */
            taxid: number;
        };
        /**
         * TaxonRef
         * @description Minimal taxon reference (breadcrumb / breakdown root).
         */
        TaxonRef: {
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /** Taxid */
            taxid: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clade_breakdown_clade__taxid__breakdown_get: {
        parameters: {
            query: {
                /** @description Rank to break the root down by. */
                rank: components["schemas"]["TargetRank"];
                sort?: components["schemas"]["SortColumn"];
                /** @description Keep only taxa with data for these resource(s). */
                filter?: components["schemas"]["MetricFilter"][] | null;
                logic?: components["schemas"]["FilterLogic"];
                exclude_empty?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clade_export_clade__taxid__export_tsv_get: {
        parameters: {
            query: {
                /** @description Rank to break the root down by. */
                rank: components["schemas"]["TargetRank"];
                sort?: components["schemas"]["SortColumn"];
                filter?: components["schemas"]["MetricFilter"][] | null;
                logic?: components["schemas"]["FilterLogic"];
                exclude_empty?: boolean;
            };
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clade_summary_clade__taxid__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CladeSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_config_metrics_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricConfig"][];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                /** @description Name query. */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taxon_lineage_taxon__taxid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonLineage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
