/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clade/{taxid}/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clade Breakdown
         * @description How a clade's data is distributed at a lower rank (Q2).
         *
         *     Descendants of `taxid` at `rank`, with filter/sort/limit pushed into a
         *     single indexed `ltree` query. Defaults mirror Euka-Survey: sort by species
         *     count, exclude empty taxa, AND-combine filters, top 25.
         */
        get: operations["clade_breakdown_clade__taxid__breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clade/{taxid}/breakdown/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clade Breakdown Quality
         * @description Per-bucket distribution stats (BUSCO / median genes / genome size / N50)
         *     for a rank breakdown — the quality lenses of the "data map". One grouped
         *     `ltree` query per source table attributes every record under the root to its
         *     rank-`rank` ancestor, then aggregates. Merge into `breakdown` by taxid.
         */
        get: operations["clade_breakdown_quality_clade__taxid__breakdown_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clade/{taxid}/export.tsv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clade Export
         * @description The full breakdown at `rank` as a streamed TSV download.
         *
         *     Same subtree query as `breakdown` but unlimited and streamed via a
         *     server-side cursor. Defaults to the complete breakdown (empties included);
         *     pass filter/exclude_empty/sort to export exactly what the table shows.
         */
        get: operations["clade_export_clade__taxid__export_tsv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clade/{taxid}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clade Summary
         * @description Genomic Resource Summary for one taxon: species count + per-resource
         *     coverage/total/percent. One indexed lookup on `clade_features`.
         */
        get: operations["clade_summary_clade__taxid__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process is up and serving. Checks no dependencies, so a
         *     container/orchestrator can tell 'process alive' apart from 'DB ready'.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness: can we actually serve reads? Pings Postgres with SELECT 1 and
         *     returns 503 if it's unreachable, so a load balancer holds traffic until the
         *     read-only serving DB is back.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Config
         * @description The tracked metrics — static card chrome the frontend renders once,
         *     keyed by the same metric keys the per-clade payloads use.
         */
        get: operations["metrics_config_metrics_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quality Config
         * @description The annotation/assembly-quality stats — static card chrome rendered once,
         *     keyed by the stat keys the per-taxon quality values use (BUSCO, gene count,
         *     genome size, N50). The analogue of ``/metrics-config`` for the new dimension.
         */
        get: operations["quality_config_quality_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Case-insensitive taxon-name search for the root picker. Substring match,
         *     prefix-matches first (served by the `pg_trgm` GIN index on `taxon.name`).
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxon/{taxid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon Lineage
         * @description The taxon and its root→node lineage (breadcrumb). One indexed `ltree`
         *     ancestor query on the materialized path.
         */
        get: operations["taxon_lineage_taxon__taxid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxon/{taxid}/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon About
         * @description A Wikipedia "About" summary for the taxon — the decorative dashboard card.
         *
         *     Resolves the taxon's scientific name, then does one cached, server-side GET
         *     against Wikipedia's REST summary endpoint (so we can send the User-Agent
         *     Wikipedia's policy wants and cache across viewers). ``404`` if the taxid is
         *     unknown; otherwise the summary, or ``null`` when there's no usable article —
         *     the frontend omits the card either way. The ``null`` result caches as a
         *     normal 200, so taxa without a page don't re-hit the network downstream.
         */
        get: operations["taxon_about_taxon__taxid__about_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxon/{taxid}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon Annotations
         * @description Functional annotations anywhere under a taxon, for the drill-down list +
         *     the live annotation-quality stats (best BUSCO, median protein-coding gene
         *     count). Subtree join to the `annotation` table; default sort surfaces the
         *     best-annotated genomes first. 404 if the taxid is unknown.
         */
        get: operations["taxon_annotations_taxon__taxid__annotations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxon/{taxid}/assemblies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon Assemblies
         * @description Genome assemblies anywhere under a taxon (the whole subtree), for the
         *     drill-down list + the live assembly-quality stats (median genome size /
         *     contig N50). One indexed `ltree` subtree join to the small `assembly` table,
         *     paginated. 404 if the taxid is unknown; an empty subtree returns `[]`.
         */
        get: operations["taxon_assemblies_taxon__taxid__assemblies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxon/{taxid}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxon Children
         * @description A taxon's direct children (adjacency), for lazy-expanding the tree.
         *
         *     One indexed `parent_id` lookup, sorted by species count by default (biggest
         *     clades first) and paginated via limit/offset so a node with tens of
         *     thousands of children loads a screenful at a time. Each child carries a
         *     `has_children` flag. 404 if the taxid is unknown; a childless taxon (e.g. a
         *     species leaf) returns an empty list.
         */
        get: operations["taxon_children_taxon__taxid__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnnotationList
         * @description Annotations under a taxon: live annotation-quality stats + a paginated list.
         */
        AnnotationList: {
            /** Items */
            items: components["schemas"]["AnnotationRecord"][];
            /** Returned */
            returned: number;
            root: components["schemas"]["TaxonRef"];
            /** Stats */
            stats: components["schemas"]["QualityStatValue"][];
            /** Total */
            total: number;
        };
        /**
         * AnnotationRecord
         * @description One functional annotation (from the ``annotation`` table), for the
         *     drill-down list — the Annotrieve-sourced BUSCO + gene metadata + GFF link.
         */
        AnnotationRecord: {
            /** Annotation Id */
            annotation_id: string;
            /** Assembly Accession */
            assembly_accession: string | null;
            /** Busco Complete */
            busco_complete: number | null;
            /** Busco Duplicated */
            busco_duplicated: number | null;
            /** Busco Lineage */
            busco_lineage: string | null;
            /** Busco Single Copy */
            busco_single_copy: number | null;
            /** Gene Count */
            gene_count: number | null;
            /** Gff Url */
            gff_url: string | null;
            /** Organism */
            organism: string;
            /** Protein Coding Count */
            protein_coding_count: number | null;
            /** Provider */
            provider: string | null;
            /** Release Date */
            release_date: string | null;
            /** Source Database */
            source_database: string | null;
            /** Taxid */
            taxid: number;
        };
        /**
         * AnnotationSort
         * @enum {string}
         */
        AnnotationSort: "busco_complete" | "protein_coding_count" | "release_date";
        /**
         * AssemblyComposition
         * @description Additive assembly-composition counts for a clade (from ``clade_features``):
         *     genome assemblies split by level, plus the reference/representative count.
         *     Summed species-only up the lineage like the s_* totals.
         */
        AssemblyComposition: {
            /** Chromosome */
            chromosome: number;
            /** Complete */
            complete: number;
            /** Contig */
            contig: number;
            /** Reference */
            reference: number;
            /** Scaffold */
            scaffold: number;
        };
        /**
         * AssemblyList
         * @description Assemblies under a taxon: live assembly-quality stats + a paginated list.
         */
        AssemblyList: {
            /** Items */
            items: components["schemas"]["AssemblyRecord"][];
            /** Returned */
            returned: number;
            root: components["schemas"]["TaxonRef"];
            /** Stats */
            stats: components["schemas"]["QualityStatValue"][];
            /** Total */
            total: number;
        };
        /**
         * AssemblyRecord
         * @description One genome assembly (from the ``assembly`` table), for the drill-down list.
         *     Fields mirror the aliased SELECT so the endpoint builds it from a dict_row.
         */
        AssemblyRecord: {
            /** Assembly Accession */
            assembly_accession: string;
            /** Assembly Level */
            assembly_level: string | null;
            /** Bioprojects */
            bioprojects: string[];
            /** Contig N50 */
            contig_n50: number | null;
            /** Download Url */
            download_url: string | null;
            /** Gc Percent */
            gc_percent: number | null;
            /** Organism */
            organism: string;
            /** Refseq Category */
            refseq_category: string | null;
            /** Release Date */
            release_date: string | null;
            /** Scaffold N50 */
            scaffold_n50: number | null;
            /** Source Database */
            source_database: string | null;
            /** Submitter */
            submitter: string | null;
            /** Taxid */
            taxid: number;
            /** Total Sequence Length */
            total_sequence_length: number | null;
        };
        /**
         * AssemblySort
         * @enum {string}
         */
        AssemblySort: "release_date" | "contig_n50" | "total_sequence_length";
        /**
         * Breakdown
         * @description The breakdown (Q2) payload: a root's descendants at a target rank.
         */
        Breakdown: {
            /** Items */
            items: components["schemas"]["CladeSummary"][];
            /** Rank */
            rank: string;
            /** Returned */
            returned: number;
            root: components["schemas"]["TaxonRef"];
            /** Total Matches */
            total_matches: number;
        };
        /**
         * BucketQuality
         * @description Per-bucket quality stats for a rank breakdown — one entry per breakdown
         *     tile that carries records, keyed by its ``taxid``. Lets the "data map" colour
         *     tiles by BUSCO / median genes / median genome size / N50 (the frontend merges
         *     these into the breakdown by taxid). ``stats`` are keyed like ``QUALITY_STATS``;
         *     a value is ``null`` when that bucket has no record carrying the field.
         */
        BucketQuality: {
            /** Stats */
            stats: components["schemas"]["QualityStatValue"][];
            /** Taxid */
            taxid: number;
        };
        /**
         * CladeSummary
         * @description The Genomic Resource Summary (Q1) payload for one taxon.
         */
        CladeSummary: {
            composition: components["schemas"]["AssemblyComposition"];
            /**
             * Is Infraspecific
             * @default false
             */
            is_infraspecific: boolean;
            /** N Rows */
            n_rows: number;
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /** Resources */
            resources: {
                [key: string]: components["schemas"]["ResourceSummary"];
            };
            /** Taxid */
            taxid: number;
        };
        /**
         * FilterLogic
         * @description How multiple resource-presence filters combine (ported verbatim).
         * @enum {string}
         */
        FilterLogic: "AND" | "OR";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MetricConfig
         * @description Static per-resource card chrome — served once by ``/metrics-config`` and
         *     joined client-side to the numbers in each per-clade payload (by ``key``).
         */
        MetricConfig: {
            /** Card Title */
            card_title: string;
            /** Card Title Help */
            card_title_help: string | null;
            /** Color */
            color: string;
            /** Coverage Column */
            coverage_column: string;
            /** External Source Name */
            external_source_name: string;
            /** External Url Template */
            external_url_template: string;
            /** Filter Label */
            filter_label: string;
            /** Key */
            key: string;
            /** Legend Label */
            legend_label: string;
            /** Overlay */
            overlay: boolean;
            /** Side */
            side: string;
            /** Sort Count Label */
            sort_count_label: string;
            /** Sort Total Label */
            sort_total_label: string;
            /** Species Help */
            species_help: string;
            /** Total Column */
            total_column: string;
            /** Total Help */
            total_help: string;
            /** Total Label */
            total_label: string;
        };
        /**
         * MetricFilter
         * @enum {string}
         */
        MetricFilter: "ass" | "ann" | "rna" | "lng";
        /**
         * QualityStatConfig
         * @description Static chrome for one quality stat — served once by ``/quality-config``
         *     and joined client-side to the per-taxon ``QualityStatValue`` by ``key``.
         *     The analogue of ``MetricConfig`` for the annotation/assembly-quality
         *     dimension (BUSCO %, gene count, genome size, N50).
         */
        QualityStatConfig: {
            /** Card Title */
            card_title: string;
            /** Fmt */
            fmt: string;
            /** Headline */
            headline: boolean;
            /** Help */
            help: string;
            /** Key */
            key: string;
            /** Source */
            source: string;
            /** Unit */
            unit: string | null;
        };
        /**
         * QualityStatValue
         * @description A quality stat computed live over a taxon's subtree records (median or
         *     max per QUALITY_STATS). ``value`` is ``null`` when the subtree has no records
         *     carrying that field.
         */
        QualityStatValue: {
            /** Key */
            key: string;
            /** Value */
            value: number | null;
        };
        /**
         * ResourceSummary
         * @description Per-resource rollup for one clade.
         */
        ResourceSummary: {
            /** Covered */
            covered: number;
            /** Percent */
            percent: number;
            /** Total */
            total: number;
        };
        /**
         * SortColumn
         * @enum {string}
         */
        SortColumn: "n_rows" | "c_ass" | "c_ann" | "c_rna" | "c_lng" | "s_ass" | "s_ann" | "s_rna" | "s_lng" | "n_ass_complete" | "n_ass_chromosome" | "n_ass_scaffold" | "n_ass_contig" | "n_reference";
        /**
         * TargetRank
         * @enum {string}
         */
        TargetRank: "phylum" | "class" | "order" | "family" | "genus" | "species";
        /**
         * TaxonAbout
         * @description Wikipedia summary for a taxon's "About" card (decorative, non-load-bearing).
         *
         *     Sourced live from Wikipedia's REST summary endpoint and cached server-side.
         *     The endpoint returns ``null`` instead of this model when the taxon has no
         *     usable article, in which case the frontend simply omits the card.
         */
        TaxonAbout: {
            /** Description */
            description: string;
            /** Extract */
            extract: string;
            /** Thumbnail */
            thumbnail: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * TaxonChildren
         * @description A taxon's direct children (adjacency) for lazy-expanding the tree.
         */
        TaxonChildren: {
            /** Items */
            items: components["schemas"]["TaxonNode"][];
            parent: components["schemas"]["TaxonRef"];
            /** Returned */
            returned: number;
            /** Total */
            total: number;
        };
        /**
         * TaxonLineage
         * @description A taxon plus its root→node lineage (for the header breadcrumb).
         */
        TaxonLineage: {
            /** Lineage */
            lineage: components["schemas"]["TaxonRef"][];
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /** Taxid */
            taxid: number;
        };
        /**
         * TaxonNode
         * @description One node in the interactive tree: a taxon's summary metrics plus a
         *     ``has_children`` hint, so the UI can show an expand affordance for a node
         *     without a second round-trip to discover it's a leaf.
         */
        TaxonNode: {
            composition: components["schemas"]["AssemblyComposition"];
            /** Has Children */
            has_children: boolean;
            /**
             * Is Infraspecific
             * @default false
             */
            is_infraspecific: boolean;
            /** N Rows */
            n_rows: number;
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /** Resources */
            resources: {
                [key: string]: components["schemas"]["ResourceSummary"];
            };
            /** Taxid */
            taxid: number;
        };
        /**
         * TaxonRef
         * @description Minimal taxon reference (breadcrumb / breakdown root).
         */
        TaxonRef: {
            /** Name */
            name: string;
            /** Rank */
            rank: string;
            /** Taxid */
            taxid: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clade_breakdown_clade__taxid__breakdown_get: {
        parameters: {
            query: {
                /** @description Rank to break the root down by. */
                rank: components["schemas"]["TargetRank"];
                sort?: components["schemas"]["SortColumn"];
                /** @description Keep only taxa with data for these resource(s). */
                filter?: components["schemas"]["MetricFilter"][] | null;
                logic?: components["schemas"]["FilterLogic"];
                exclude_empty?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clade_breakdown_quality_clade__taxid__breakdown_quality_get: {
        parameters: {
            query: {
                /** @description Rank the root is broken down by. */
                rank: components["schemas"]["TargetRank"];
            };
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketQuality"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clade_export_clade__taxid__export_tsv_get: {
        parameters: {
            query: {
                /** @description Rank to break the root down by. */
                rank: components["schemas"]["TargetRank"];
                sort?: components["schemas"]["SortColumn"];
                filter?: components["schemas"]["MetricFilter"][] | null;
                logic?: components["schemas"]["FilterLogic"];
                exclude_empty?: boolean;
            };
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clade_summary_clade__taxid__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CladeSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_config_metrics_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricConfig"][];
                };
            };
        };
    };
    quality_config_quality_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityStatConfig"][];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                /** @description Name query. */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taxon_lineage_taxon__taxid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonLineage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taxon_about_taxon__taxid__about_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonAbout"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taxon_annotations_taxon__taxid__annotations_get: {
        parameters: {
            query?: {
                sort?: components["schemas"]["AnnotationSort"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taxon_assemblies_taxon__taxid__assemblies_get: {
        parameters: {
            query?: {
                sort?: components["schemas"]["AssemblySort"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taxon_children_taxon__taxid__children_get: {
        parameters: {
            query?: {
                sort?: components["schemas"]["SortColumn"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                taxid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonChildren"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
